# Generated by Django 5.2.15 on 2026-06-06 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ section',
                'verbose_name_plural': 'FAQ sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('chancery', 'The Chancery Hotel'), ('pavilion', 'Chancery Pavilion')], unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, help_text='e.g. Lavelle Road', max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, help_text='Digits only, no +', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rooms_count', models.PositiveIntegerField(default=0)),
                ('established', models.CharField(blank=True, max_length=20)),
                ('location_tag', models.CharField(blank=True, help_text='e.g. Flagship, Heritage', max_length=60)),
                ('synxis_id', models.CharField(blank=True, max_length=20)),
                ('tripadvisor_url', models.URLField(blank=True)),
                ('tripadvisor_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('tripadvisor_count', models.PositiveIntegerField(blank=True, null=True)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('google_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('intro_heading', models.CharField(blank=True, max_length=200)),
                ('intro_body', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Chancery Hotels', max_length=200)),
                ('tagline', models.CharField(default='Luxury Hotels in Bangalore', max_length=300)),
                ('meta_description', models.TextField(default='The Chancery Group of Hotels: Premium luxury hotels in Bangalore offering world-class rooms, fine dining, event venues & exclusive packages.')),
                ('footer_note', models.TextField(blank=True)),
                ('newsletter_heading', models.CharField(default='Stay in touch', max_length=200)),
                ('newsletter_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tripadvisor_url', models.URLField(blank=True)),
                ('synxis_chain_id', models.CharField(default='18850', max_length=20)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, help_text="e.g. 'Anniversary Stay'", max_length=200)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.faqsection')),
            ],
            options={
                'verbose_name': 'FAQ item',
                'verbose_name_plural': 'FAQ items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hotel', 'Hotel'), ('lobby', 'Lobby'), ('rooms', 'Rooms'), ('dining', 'Dining'), ('events', 'Events')], default='hotel', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(blank=True, help_text='Leave blank for shared brand images.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.hotel')),
            ],
            options={
                'ordering': ['hotel__order', 'category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, help_text='Short label, e.g. Early Bird', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('promo_code', models.CharField(blank=True, help_text='SynXis promo code', max_length=40)),
                ('min_nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(blank=True, help_text='Leave blank for shared offers that apply to both properties.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='content.hotel')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('home', 'Brand home'), ('rooms', 'All rooms'), ('faq', 'FAQ'), ('careers', 'Careers'), ('catering', 'Catering'), ('privacy', 'Privacy'), ('terms', 'Terms'), ('accessibility', 'Accessibility'), ('sitemap', 'Site map'), ('hotel_home', 'Hotel home'), ('accommodation', 'Accommodation'), ('dining', 'Dining'), ('events', 'Plan your event'), ('offers', 'Special offers'), ('gallery', 'Gallery'), ('contact', 'Contact us'), ('experience', 'Experience'), ('destination', 'Destination')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120)),
                ('hero_heading', models.CharField(blank=True, max_length=300)),
                ('hero_subheading', models.TextField(blank=True)),
                ('intro_body', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.hotel')),
            ],
            options={
                'ordering': ['kind'],
                'unique_together': {('kind', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text block'), ('text_image', 'Text + image'), ('image_text', 'Image + text'), ('callout', 'Callout / quote'), ('cta', 'Call to action')], default='text', max_length=20)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('cuisine', models.CharField(blank=True, max_length=200)),
                ('timing', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='dining/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='content.hotel')),
            ],
            options={
                'ordering': ['hotel__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dining/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.restaurant')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('size_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True, help_text='One per line. Rendered as a list.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('book_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='content.hotel')),
            ],
            options={
                'verbose_name_plural': 'Room categories',
                'ordering': ['hotel__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.roomcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('kind', models.CharField(blank=True, choices=[('ballroom', 'Ballroom'), ('banquet', 'Banquet'), ('conference', 'Conference Suite'), ('private_dining', 'Private Dining'), ('executive', 'Executive Boardroom'), ('al_fresco', 'Al Fresco'), ('divisible', 'Divisible Hall')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 96 x 53 ft', max_length=120)),
                ('ceiling_ft', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('guests_max', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_theatre', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_banquet', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_classroom', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_ushape', models.PositiveIntegerField(blank=True, null=True)),
                ('cap_cocktail', models.PositiveIntegerField(blank=True, null=True)),
                ('half_day_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('full_day_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('per_plate_inr', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='content.hotel')),
            ],
            options={
                'ordering': ['hotel__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.venue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
