# Generated by Django 5.2.15 on 2026-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text="Master 'Chancery Hotels' group logo. Shown in the navbar on all brand-level pages, and in the footer.", null=True, upload_to='brand/'),
        ),
    ]
