# Generated by Django 5.2.15 on 2026-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitecontent_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='fax',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_alt',
            field=models.CharField(blank=True, help_text="Secondary / board line, e.g. 'Board: 080-69894666'.", max_length=80),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary line, shown everywhere.', max_length=40),
        ),
    ]
