# Generated by Django 5.2.15 on 2026-06-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('interest', models.CharField(choices=[('stay', 'Stay / Room booking'), ('dining', 'Dining reservation'), ('event', 'Event or wedding'), ('catering', 'Outdoor catering'), ('careers', 'Careers'), ('other', 'Other')], default='stay', max_length=40)),
                ('hotel_interest', models.CharField(choices=[('chancery', 'The Chancery Hotel'), ('pavilion', 'Chancery Pavilion'), ('either', 'No preference')], default='either', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, help_text='Page or context the lead was submitted from.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter subscriber',
                'ordering': ['-created_at'],
            },
        ),
    ]
