# Generated by Django 5.2.15 on 2026-06-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(choices=[('chancery', 'The Chancery Hotel'), ('pavilion', 'Chancery Pavilion'), ('both', 'Both / Brand-level')], max_length=20)),
                ('department', models.CharField(choices=[('reservations', 'Reservations'), ('sales', 'Sales'), ('events', 'Meetings & Events'), ('catering', 'Outdoor Catering'), ('careers', 'Careers'), ('general', 'General Enquiry')], max_length=30)),
                ('notify_email', models.EmailField(help_text='Primary inbox for this enquiry type.', max_length=254)),
                ('cc_emails', models.CharField(blank=True, help_text='Optional extra recipients, comma-separated.', max_length=400)),
                ('whatsapp_number', models.CharField(blank=True, help_text="Digits incl. country code, no '+'. Team WhatsApp alerts (used later).", max_length=20)),
                ('slack_webhook', models.URLField(blank=True, help_text='Optional Slack/Teams incoming webhook for fast alerts.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department contact (routing)',
                'verbose_name_plural': 'Department contacts (routing)',
                'ordering': ['hotel', 'department'],
                'unique_together': {('hotel', 'department')},
            },
        ),
    ]
