# Generated by Django 5.2.15 on 2026-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_departmentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentcontact',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional direct line shown to guests for this department.', max_length=40),
        ),
        migrations.AddField(
            model_name='departmentcontact',
            name='public',
            field=models.BooleanField(default=True, help_text="Show this department's email/phone publicly on the contact page."),
        ),
    ]
