# Generated by Django 5.2.15 on 2026-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_departmentcontact_phone_departmentcontact_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='routed_to',
            field=models.CharField(blank=True, help_text='Where the enquiry was emailed (audit trail).', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
