# Generated by Django 5.2.15 on 2026-06-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_routed_to_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='covers',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of guests.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='restaurant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='departmentcontact',
            name='department',
            field=models.CharField(choices=[('reservations', 'Reservations'), ('dining', 'Dining'), ('sales', 'Sales'), ('events', 'Meetings & Events'), ('catering', 'Outdoor Catering'), ('careers', 'Careers'), ('general', 'General Enquiry')], max_length=30),
        ),
    ]
