# Generated by Django 5.2.15 on 2026-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_covers_lead_preferred_date_lead_preferred_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='event_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
